# Generated by Django 5.0.4 on 2024-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_db',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
