# Generated by Django 5.0.4 on 2024-05-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_category_db_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Product_Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Product_Photo', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
